---
title: "Représentations_graphiques_donnees_disponibles"
author: "Julia"
date: "2026-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# représenter stations aspe des départements 14 et 27
Ce code est à faire tourner apres le code du notebook 01_Construction_jeux_donnees_ASPE_station

```{r}
aspe_nor_sandre_1427<- aspe_nor_sandre%>%
  filter(dept %in% c("14","27"))
```


```{r}
graph_aspe_nor_sandre_1427 <-ggplot(data=aspe_nor_sandre_1427, aes(x = annee, y=as.character(sta_libelle_sandre),
             fill= RESEAUX)) + 
  geom_tile() +
  labs(title = "Disponibilité des données ASPE, pour les stations sélectionnées et les réseaux associés, par années",
       subtitle = "Départements 14 et 27", 
       x ="Années",
       y = "",
       fill = "Réseaux") + 
  theme(plot.title = element_text(size=11),
        plot.subtitle = element_text(size=10),
        axis.title.x=element_text(size=8),
        axis.text.x=element_text(size=8),
        axis.text.y = element_text(size=9),
        legend.title=element_text(size=8),
        legend.text=element_text(size = 8),
        legend.position = "bottom")+
  guides(fill=guide_legend(nrow=1)) 
```

```{r}
ggsave("graph_aspe_nor_sandre_1427.pdf", plot=graph_aspe_nor_sandre_1427, width=12, height=8)
```

# représenter stations aspe des départements 50, 61 et 76
```{r}
aspe_nor_sandre_506176<- aspe_nor_sandre%>%
  filter(dept %in% c("50","61","76"))
```


```{r}
graph_aspe_nor_sandre_506176 <-ggplot(data=aspe_nor_sandre_506176, aes(x = annee, y=as.character(sta_libelle_sandre),
             fill= RESEAUX)) + 
  geom_tile() +
  labs(title = "Les stations sélectionnées et les réseaux associés par années",
       subtitle = "Départements 50, 61 et 76", 
       x ="Années",
       y = "",
       fill = "Réseaux") + 
  theme(plot.title = element_text(size=11),
        plot.subtitle = element_text(size=10),
        axis.title.x=element_text(size=8),
        axis.text.x=element_text(size=8),
        axis.text.y = element_text(size=9),
        legend.title=element_text(size=8),
        legend.text=element_text(size = 8),
        legend.position = "bottom")+
  guides(fill=guide_legend(nrow=1)) 
```

```{r}
ggsave("graph_aspe_nor_sandre_506176.pdf", plot=graph_aspe_nor_sandre_506176, width=12, height=8)
```

# représenter indices hydrobio des départements 14 et 27
```{r}
indices_presence_1427 <- indices_presence %>%
  filter(code_departement %in% c("14","27"))
```

```{r}
graph_indices_presence_1427 <- ggplot(indices_presence_1427, aes(x=annee, y= libelle_station_hydrobio, fill= nb_indices))+
  geom_tile()+
  scale_fill_manual(
    values = c("0"="white", "1"="yellow", "2"="orange","3"="red"),
    name= "Nombre d'indices disponibles")+
  theme_minimal()+
  labs(
    x="Années",
    y="",
    title="Disponibilité des indices (I2M2, IBD, IBMR) par station et par année",
    subtitle = "Départements 14 et 27"
  )+
  theme(plot.title = element_text(size=11),
        plot.subtitle = element_text(size=10),
        axis.title.x=element_text(size=8),
        axis.text.x=element_text(size=8),
        axis.text.y = element_text(size=9),
        legend.title=element_text(size=8),
        legend.text=element_text(size = 8),
        legend.position = "bottom")+
  guides(fill=guide_legend(nrow=1))+
  scale_x_continuous(breaks=seq(min(indices_presence$annee),max(indices_presence$annee)))
```
```{r}
ggsave("graph_indices_presence_1427.pdf", plot=graph_indices_presence_1427, width=12, height=8)
```

# représenter indices hydrobio des départements 50, 61 et 76
```{r}
indices_presence_506176 <- indices_presence %>%
  filter(code_departement %in% c("50","61","76"))
```

```{r}
graph_indices_presence_506176 <- ggplot(indices_presence_506176, aes(x=annee, y= libelle_station_hydrobio, fill= nb_indices))+
  geom_tile()+
  scale_fill_manual(
    values = c("0"="white", "1"="yellow", "2"="orange","3"="red"),
    name= "Nombre d'indices disponibles")+
  theme_minimal()+
  labs(
    x="Années",
    y="",
    title="Disponibilité des indices (I2M2, IBD, IBMR) par station et par année",
    subtitle = "Départements 50, 61 et 76"
  )+
  theme(plot.title = element_text(size=11),
        plot.subtitle = element_text(size=10),
        axis.title.x=element_text(size=8),
        axis.text.x=element_text(size=8),
        axis.text.y = element_text(size=9),
        legend.title=element_text(size=8),
        legend.text=element_text(size = 8),
        legend.position = "bottom")+
  guides(fill=guide_legend(nrow=1))+
  scale_x_continuous(breaks=seq(min(indices_presence$annee),max(indices_presence$annee)))
```
```{r}
ggsave("graph_indices_presence_506176.pdf", plot=graph_indices_presence_506176, width=12, height=8)
```
